### PR TITLE
Inclusion of the history of kubernetes

### PR DESCRIPTION
**Pull request by Abhiram-Gullapalli**
Created a separate file.

### CODE REVIEW

**Review by cnu1812 — COMMENTED** [review]
Everything is written in just two lines, it's kinda awkward

**Comment by gullapalli9482** [comment]
Is it ive just copied it from my notepad , I'll change it

**Review by AbhijithGanesh — APPROVED** [review]
Good start , we can update more content as we progress

**Comment by AbhijithGanesh** [comment]
@cnu1812 Please look forward to add more content

**Comment by AbhijithGanesh** [comment]
Closes issue #81

**Comment by AbhijithGanesh** [comment]
@vish-han can you add your content to this?

**Comment by vish-han** [comment]
Yes , I would love to 👍

**Pull request merged**
